services:
  postgres:
    image: postgres:15
    container_name: currency_exchanger_db
    environment:
      POSTGRES_DB: currency_exchanger
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
